using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using SpotFinder.BuildingBlocks.Api;
using SpotFinder.FeedService.Application.Features.Feed.Queries.Common;
using SpotFinder.FeedService.Infrastructure.Persistence;
using System.Diagnostics;

namespace SpotFinder.FeedService.Application.Features.Feed.Queries.GetNearbyFeed;

public sealed class GetNearbyFeedQueryHandler
    : IRequestHandler<GetNearbyFeedQuery, ApiResult<FeedResponse>>
{
    private readonly FeedQueryDbContext _db;
    private readonly IMemoryCache       _cache;
    private readonly ILogger<GetNearbyFeedQueryHandler> _logger;

    private static readonly TimeSpan CacheTtl = TimeSpan.FromSeconds(30);
    private const int OversampleFactor = 3;

    public GetNearbyFeedQueryHandler(
        FeedQueryDbContext db,
        IMemoryCache cache,
        ILogger<GetNearbyFeedQueryHandler> logger)
    {
        _db     = db;
        _cache  = cache;
        _logger = logger;
    }

    public async Task<ApiResult<FeedResponse>> Handle(
        GetNearbyFeedQuery request, CancellationToken ct)
    {
        var sw       = Stopwatch.StartNew();
        var pageSize = Math.Clamp(request.PageSize, 1, 50);
        var hasCursor = request.CursorScore.HasValue
                     && request.CursorCreatedAt.HasValue
                     && request.CursorPostId.HasValue;

        _logger.LogInformation(
            "GetNearbyFeed — userId={UserId} cityId={CityId} pageSize={PageSize} hasCursor={HasCursor}",
            request.UserId, request.CityId, pageSize, hasCursor);

        // ── Cache check (first page, per user for isLiked correctness) ─────────
        var cacheKey = $"feed:nearby:{request.UserId}:{request.CityId}:{pageSize}";
        if (!hasCursor && _cache.TryGetValue(cacheKey, out FeedResponse? cached))
        {
            _logger.LogInformation(
                "GetNearbyFeed — cache HIT key={Key} in {Ms}ms", cacheKey, sw.ElapsedMilliseconds);
            return ApiResult<FeedResponse>.Ok(cached!);
        }
        _logger.LogInformation("GetNearbyFeed — cache MISS key={Key}", cacheKey);

        var cs  = request.CursorScore     ?? 0;
        var cAt = request.CursorCreatedAt ?? DateTime.MinValue;
        var cId = request.CursorPostId    ?? Guid.Empty;

        // ── STEP 1: Cursor-paginated posts in a city — precomputed feed_score ─
        //
        // SQL (generated by EF Core):
        //   SELECT p.id, p.user_id, p.place_id, p.caption,
        //          p.like_count, p.comment_count, p.feed_score, p.created_at
        //   FROM content.posts p
        //   INNER JOIN place.places pl ON p.place_id = pl.id
        //   WHERE pl.city_id = @cityId
        //     AND p.is_deleted = false AND p.status != 'hidden'
        //     AND pl.is_deleted = false
        //     [AND cursor condition]
        //   ORDER BY p.feed_score DESC, p.created_at DESC, p.id DESC
        //   LIMIT @pageSize * OversampleFactor

        var rawPosts = await (
            from p  in _db.Posts
            join pl in _db.Places on p.PlaceId equals pl.Id
            where pl.CityId == request.CityId
            where !hasCursor
                  || p.FeedScore < cs
                  || (p.FeedScore == cs && p.CreatedAt < cAt)
                  || (p.FeedScore == cs && p.CreatedAt == cAt && p.Id < cId)
            orderby p.FeedScore descending, p.CreatedAt descending, p.Id descending
            select new
            {
                p.Id, p.UserId, p.PlaceId,
                p.Caption, p.LikeCount, p.CommentCount, p.CreatedAt,
                p.FeedScore
            }
        )
        .Take(pageSize * OversampleFactor)
        .ToListAsync(ct);

        if (rawPosts.Count == 0)
        {
            var empty = new FeedResponse([], null, HasMore: false);
            if (!hasCursor) _cache.Set(cacheKey, empty, CacheTtl);
            return ApiResult<FeedResponse>.Ok(empty);
        }

        // ── STEP 2: Feed diversity — max 2 posts per user ─────────────────────
        var posts = rawPosts
            .GroupBy(p => p.UserId)
            .SelectMany(g => g.Take(2))
            .OrderByDescending(p => p.FeedScore)
            .ThenByDescending(p => p.CreatedAt)
            .ThenByDescending(p => p.Id)
            .Take(pageSize)
            .ToList();

        var postIds  = posts.Select(p => p.Id).ToList();
        var userIds  = posts.Select(p => p.UserId).Distinct().ToList();
        var placeIds = posts.Select(p => p.PlaceId).Distinct().ToList();

        // ── STEP 3: Bulk loads ────────────────────────────────────────────────
        var mediaList = await _db.PostMedia
            .Where(m => postIds.Contains(m.PostId))
            .Select(m => new { m.PostId, m.Url })
            .ToListAsync(ct);

        var userList = await (
            from u in _db.Users
            where userIds.Contains(u.Id)
            join pr in _db.UserProfiles on u.Id equals pr.UserId into prg
            from pr in prg.DefaultIfEmpty()
            select new
            {
                u.Id, u.Username,
                DisplayName     = pr != null ? pr.DisplayName     : null,
                ProfileImageUrl = pr != null ? pr.ProfileImageUrl : null
            }
        ).ToListAsync(ct);

        var placeList = await _db.PlaceTranslations
            .Where(t => placeIds.Contains(t.PlaceId))
            .Select(t => new { t.PlaceId, t.LanguageId, t.Name })
            .ToListAsync(ct);

        var likedList = await _db.PostLikes
            .Where(l => l.UserId == request.UserId && postIds.Contains(l.PostId))
            .Select(l => l.PostId)
            .ToListAsync(ct);

        // ── STEP 4: In-memory projection ──────────────────────────────────────
        var mediaByPost = mediaList
            .GroupBy(m => m.PostId)
            .ToDictionary(g => g.Key,
                          g => (IReadOnlyList<string>)g.Select(m => m.Url).ToList());

        var userById = userList.ToDictionary(u => u.Id);

        var nameByPlace = placeList
            .GroupBy(t => t.PlaceId)
            .ToDictionary(
                g => g.Key,
                g => (g.FirstOrDefault(t => t.LanguageId == 1) ?? g.First()).Name);

        var likedSet = likedList.ToHashSet();

        var dtos = posts.Select(p =>
        {
            userById.TryGetValue(p.UserId, out var u);
            return new FeedPostDto(
                p.Id,
                new FeedUserDto(p.UserId,
                    u?.Username ?? string.Empty,
                    u?.DisplayName,
                    u?.ProfileImageUrl),
                new FeedPlaceDto(p.PlaceId,
                    nameByPlace.GetValueOrDefault(p.PlaceId, string.Empty)),
                p.Caption,
                mediaByPost.GetValueOrDefault(p.Id, []),
                p.LikeCount,
                p.CommentCount,
                p.CreatedAt,
                likedSet.Contains(p.Id));
        }).ToList();

        var last     = posts[^1];
        var cursor   = new FeedCursor(last.FeedScore, last.CreatedAt, last.Id);
        var hasMore  = posts.Count == pageSize;
        var response = new FeedResponse(dtos, hasMore ? cursor : null, hasMore);

        if (!hasCursor) _cache.Set(cacheKey, response, CacheTtl);

        sw.Stop();
        _logger.LogInformation(
            "GetNearbyFeed — {Count} posts, hasMore={HasMore} in {Ms}ms",
            dtos.Count, hasMore, sw.ElapsedMilliseconds);

        return ApiResult<FeedResponse>.Ok(response);
    }
}
