using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using SpotFinder.BuildingBlocks.Api;
using SpotFinder.FeedService.Application.Features.Feed.Queries.Common;
using SpotFinder.FeedService.Infrastructure.Persistence;
using System.Diagnostics;

namespace SpotFinder.FeedService.Application.Features.Feed.Queries.GetPlaceFeed;

public sealed class GetPlaceFeedQueryHandler
    : IRequestHandler<GetPlaceFeedQuery, ApiResult<FeedResponse>>
{
    private readonly FeedQueryDbContext _db;
    private readonly IMemoryCache       _cache;
    private readonly ILogger<GetPlaceFeedQueryHandler> _logger;

    private static readonly TimeSpan CacheTtl = TimeSpan.FromSeconds(60);
    private const int OversampleFactor = 3;

    public GetPlaceFeedQueryHandler(
        FeedQueryDbContext db,
        IMemoryCache cache,
        ILogger<GetPlaceFeedQueryHandler> logger)
    {
        _db     = db;
        _cache  = cache;
        _logger = logger;
    }

    public async Task<ApiResult<FeedResponse>> Handle(
        GetPlaceFeedQuery request, CancellationToken ct)
    {
        var sw       = Stopwatch.StartNew();
        var pageSize = Math.Clamp(request.PageSize, 1, 50);
        var hasCursor = request.CursorScore.HasValue
                     && request.CursorCreatedAt.HasValue
                     && request.CursorPostId.HasValue;

        _logger.LogInformation(
            "GetPlaceFeed — userId={UserId} placeId={PlaceId} pageSize={PageSize} hasCursor={HasCursor}",
            request.UserId, request.PlaceId, pageSize, hasCursor);

        // ── Cache check (first page only, 60s TTL) ────────────────────────────
        var cacheKey = $"feed:place:{request.UserId}:{request.PlaceId}:{pageSize}";
        if (!hasCursor && _cache.TryGetValue(cacheKey, out FeedResponse? cached))
        {
            _logger.LogInformation(
                "GetPlaceFeed — cache HIT key={Key} in {Ms}ms", cacheKey, sw.ElapsedMilliseconds);
            return ApiResult<FeedResponse>.Ok(cached!);
        }
        _logger.LogInformation("GetPlaceFeed — cache MISS key={Key}", cacheKey);

        var cs  = request.CursorScore     ?? 0;
        var cAt = request.CursorCreatedAt ?? DateTime.MinValue;
        var cId = request.CursorPostId    ?? Guid.Empty;

        // ── STEP 1: Cursor-paginated posts for a specific place ─────────────
        //
        // Phase 6.2: uses precomputed feed_score column.
        // Oversample for diversity (some places may have a dominant poster).
        //
        // SQL (generated by EF Core):
        //   SELECT p.id, p.user_id, p.place_id, p.caption,
        //          p.like_count, p.comment_count, p.feed_score, p.created_at
        //   FROM content.posts p
        //   WHERE p.place_id = @placeId
        //     AND p.is_deleted = false AND p.status != 'hidden'
        //     [AND cursor condition]
        //   ORDER BY p.feed_score DESC, p.created_at DESC, p.id DESC
        //   LIMIT @pageSize * OversampleFactor

        var rawPosts = await _db.Posts
            .Where(p => p.PlaceId == request.PlaceId)
            .Where(p => !hasCursor
                        || p.FeedScore < cs
                        || (p.FeedScore == cs && p.CreatedAt < cAt)
                        || (p.FeedScore == cs && p.CreatedAt == cAt && p.Id < cId))
            .OrderByDescending(p => p.FeedScore)
            .ThenByDescending(p => p.CreatedAt)
            .ThenByDescending(p => p.Id)
            .Take(pageSize * OversampleFactor)
            .Select(p => new
            {
                p.Id, p.UserId, p.PlaceId,
                p.Caption, p.LikeCount, p.CommentCount, p.CreatedAt,
                p.FeedScore
            })
            .ToListAsync(ct);

        if (rawPosts.Count == 0)
        {
            var empty = new FeedResponse([], null, HasMore: false);
            if (!hasCursor) _cache.Set(cacheKey, empty, CacheTtl);
            return ApiResult<FeedResponse>.Ok(empty);
        }

        // ── STEP 2: Feed diversity — max 2 posts per user ─────────────────────
        var posts = rawPosts
            .GroupBy(p => p.UserId)
            .SelectMany(g => g.Take(2))
            .OrderByDescending(p => p.FeedScore)
            .ThenByDescending(p => p.CreatedAt)
            .ThenByDescending(p => p.Id)
            .Take(pageSize)
            .ToList();

        var postIds = posts.Select(p => p.Id).ToList();
        var userIds = posts.Select(p => p.UserId).Distinct().ToList();

        // ── STEP 3: Bulk loads ────────────────────────────────────────────────
        var mediaList = await _db.PostMedia
            .Where(m => postIds.Contains(m.PostId))
            .Select(m => new { m.PostId, m.Url })
            .ToListAsync(ct);

        var userList = await (
            from u in _db.Users
            where userIds.Contains(u.Id)
            join pr in _db.UserProfiles on u.Id equals pr.UserId into prg
            from pr in prg.DefaultIfEmpty()
            select new
            {
                u.Id, u.Username,
                DisplayName     = pr != null ? pr.DisplayName     : null,
                ProfileImageUrl = pr != null ? pr.ProfileImageUrl : null
            }
        ).ToListAsync(ct);

        // Single place → one optimised query instead of multi-place GroupBy
        var placeName = await _db.PlaceTranslations
            .Where(t => t.PlaceId == request.PlaceId)
            .OrderBy(t => t.LanguageId == 1 ? 0 : 1)
            .ThenBy(t => t.LanguageId)
            .Select(t => t.Name)
            .FirstOrDefaultAsync(ct) ?? string.Empty;

        var likedList = await _db.PostLikes
            .Where(l => l.UserId == request.UserId && postIds.Contains(l.PostId))
            .Select(l => l.PostId)
            .ToListAsync(ct);

        // ── STEP 4: In-memory projection ──────────────────────────────────────
        var mediaByPost = mediaList
            .GroupBy(m => m.PostId)
            .ToDictionary(g => g.Key,
                          g => (IReadOnlyList<string>)g.Select(m => m.Url).ToList());

        var userById  = userList.ToDictionary(u => u.Id);
        var likedSet  = likedList.ToHashSet();
        var placeDto  = new FeedPlaceDto(request.PlaceId, placeName);

        var dtos = posts.Select(p =>
        {
            userById.TryGetValue(p.UserId, out var u);
            return new FeedPostDto(
                p.Id,
                new FeedUserDto(p.UserId,
                    u?.Username ?? string.Empty,
                    u?.DisplayName,
                    u?.ProfileImageUrl),
                placeDto,
                p.Caption,
                mediaByPost.GetValueOrDefault(p.Id, []),
                p.LikeCount,
                p.CommentCount,
                p.CreatedAt,
                likedSet.Contains(p.Id));
        }).ToList();

        var last     = posts[^1];
        var cursor   = new FeedCursor(last.FeedScore, last.CreatedAt, last.Id);
        var hasMore  = posts.Count == pageSize;
        var response = new FeedResponse(dtos, hasMore ? cursor : null, hasMore);

        if (!hasCursor) _cache.Set(cacheKey, response, CacheTtl);

        sw.Stop();
        _logger.LogInformation(
            "GetPlaceFeed — {Count} posts, hasMore={HasMore} in {Ms}ms",
            dtos.Count, hasMore, sw.ElapsedMilliseconds);

        return ApiResult<FeedResponse>.Ok(response);
    }
}
