import { create } from 'zustand';
import { UserProfile } from '../types';
import { clearAll, saveToken, saveRefreshToken } from '../utils/storage';
import { setAuthToken, clearAuthToken } from '../api/client';
import { identifySentryUser, clearSentryUser } from '../utils/sentry';

interface AuthState {
  token: string | null;
  user: UserProfile | null;
  isAuthenticated: boolean;
  isHydrated: boolean;
  needsUsernameSetup: boolean;

  setAuth: (token: string, refreshToken: string, user: UserProfile) => Promise<void>;
  setUser: (user: UserProfile) => void;
  logout: () => Promise<void>;
  setHydrated: () => void;
  setNeedsUsernameSetup: (value: boolean) => void;
}

function isAutoGeneratedUsername(username: string): boolean {
  return /^user\d*$/.test(username);
}

export const useAuthStore = create<AuthState>((set) => ({
  token: null,
  user: null,
  isAuthenticated: false,
  isHydrated: false,
  needsUsernameSetup: false,

  setAuth: async (token, refreshToken, user) => {
    await saveToken(token);
    await saveRefreshToken(refreshToken);
    setAuthToken(token);
    identifySentryUser(user.id, user.email);
    set({
      token,
      user,
      isAuthenticated: true,
      needsUsernameSetup: isAutoGeneratedUsername(user.username ?? ''),
    });
  },

  setNeedsUsernameSetup: (value) => set({ needsUsernameSetup: value }),

  setUser: (user) => set({ user }),

  logout: async () => {
    await clearAll();
    clearAuthToken();
    clearSentryUser();
    set({ token: null, user: null, isAuthenticated: false });
  },

  setHydrated: () => set({ isHydrated: true }),
}));
