using MediatR;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using SpotFinder.BuildingBlocks.Api;
using SpotFinder.FeedService.Application.Features.Feed.Queries.Common;
using SpotFinder.FeedService.Infrastructure.Persistence;
using System.Diagnostics;

namespace SpotFinder.FeedService.Application.Features.Feed.Queries.GetFollowingFeed;

public sealed class GetFollowingFeedQueryHandler
    : IRequestHandler<GetFollowingFeedQuery, ApiResult<FeedResponse>>
{
    private readonly FeedQueryDbContext _db;
    private readonly IMemoryCache       _cache;
    private readonly ILogger<GetFollowingFeedQueryHandler> _logger;

    private static readonly TimeSpan CacheTtl = TimeSpan.FromSeconds(30);

    // Oversample factor for diversity filtering — fetch 3× so that the
    // max-2-per-user rule still fills a full page in almost all real distributions.
    private const int OversampleFactor = 3;

    public GetFollowingFeedQueryHandler(
        FeedQueryDbContext db,
        IMemoryCache cache,
        ILogger<GetFollowingFeedQueryHandler> logger)
    {
        _db     = db;
        _cache  = cache;
        _logger = logger;
    }

    public async Task<ApiResult<FeedResponse>> Handle(
        GetFollowingFeedQuery request, CancellationToken ct)
    {
        var sw       = Stopwatch.StartNew();
        var pageSize = Math.Clamp(request.PageSize, 1, 50);
        var hasCursor = request.CursorScore.HasValue
                     && request.CursorCreatedAt.HasValue
                     && request.CursorPostId.HasValue;

        _logger.LogInformation(
            "GetFollowingFeed — userId={UserId} pageSize={PageSize} hasCursor={HasCursor}",
            request.UserId, pageSize, hasCursor);

        // ── Cache check (first page only) ─────────────────────────────────────
        var cacheKey = $"feed:following:{request.UserId}:{pageSize}";
        if (!hasCursor && _cache.TryGetValue(cacheKey, out FeedResponse? cached))
        {
            _logger.LogInformation(
                "GetFollowingFeed — cache HIT key={Key} in {Ms}ms", cacheKey, sw.ElapsedMilliseconds);
            return ApiResult<FeedResponse>.Ok(cached!);
        }
        _logger.LogInformation("GetFollowingFeed — cache MISS key={Key}", cacheKey);

        var cs  = request.CursorScore     ?? 0;
        var cAt = request.CursorCreatedAt ?? DateTime.MinValue;
        var cId = request.CursorPostId    ?? Guid.Empty;

        // ── STEP 1: Cursor-paginated posts from followed users ─────────────────
        //
        // Phase 6.2: ORDER BY p.feed_score (precomputed) — no inline CASE WHEN.
        // Oversample by OversampleFactor to allow in-memory diversity trimming.
        //
        // SQL (generated by EF Core):
        //   SELECT p.id, p.user_id, p.place_id, p.caption,
        //          p.like_count, p.comment_count, p.feed_score, p.created_at
        //   FROM content.posts p
        //   INNER JOIN social.user_follows f ON p.user_id = f.following_id
        //   WHERE f.follower_id = @userId
        //     AND p.is_deleted = false AND p.status != 'hidden'   ← query filter
        //     [AND (p.feed_score < @cs
        //          OR (p.feed_score = @cs AND p.created_at < @cAt)
        //          OR (p.feed_score = @cs AND p.created_at = @cAt AND p.id < @cId))]
        //   ORDER BY p.feed_score DESC, p.created_at DESC, p.id DESC
        //   LIMIT @pageSize * OversampleFactor

        var rawPosts = await (
            from p in _db.Posts
            join f in _db.UserFollows on p.UserId equals f.FollowingId
            where f.FollowerId == request.UserId
            where !hasCursor
                  || p.FeedScore < cs
                  || (p.FeedScore == cs && p.CreatedAt < cAt)
                  || (p.FeedScore == cs && p.CreatedAt == cAt && p.Id < cId)
            orderby p.FeedScore descending, p.CreatedAt descending, p.Id descending
            select new
            {
                p.Id, p.UserId, p.PlaceId,
                p.Caption, p.LikeCount, p.CommentCount, p.CreatedAt,
                p.FeedScore
            }
        )
        .Take(pageSize * OversampleFactor)
        .ToListAsync(ct);

        // ── STEP 1b: Cold start fallback ───────────────────────────────────────
        //
        // New user with no follows → empty rawPosts on first page.
        // Serve global top-scored posts instead.
        bool isFallback = false;
        if (rawPosts.Count == 0 && !hasCursor)
        {
            _logger.LogInformation(
                "GetFollowingFeed — cold start fallback for userId={UserId}", request.UserId);

            rawPosts = await _db.Posts
                .OrderByDescending(p => p.FeedScore)
                .ThenByDescending(p => p.CreatedAt)
                .ThenByDescending(p => p.Id)
                .Take(pageSize * OversampleFactor)
                .Select(p => new
                {
                    p.Id, p.UserId, p.PlaceId,
                    p.Caption, p.LikeCount, p.CommentCount, p.CreatedAt,
                    p.FeedScore
                })
                .ToListAsync(ct);

            isFallback = true;
        }

        if (rawPosts.Count == 0)
        {
            var empty = new FeedResponse([], null, HasMore: false);
            if (!hasCursor) _cache.Set(cacheKey, empty, CacheTtl);
            return ApiResult<FeedResponse>.Ok(empty);
        }

        // ── STEP 2: Feed diversity — max 2 posts per user ─────────────────────
        //
        // Applied in-memory on the oversampled batch.
        // GroupBy preserves order within each group (we ordered DESC above).
        var posts = rawPosts
            .GroupBy(p => p.UserId)
            .SelectMany(g => g.Take(2))
            .OrderByDescending(p => p.FeedScore)
            .ThenByDescending(p => p.CreatedAt)
            .ThenByDescending(p => p.Id)
            .Take(pageSize)
            .ToList();

        var postIds  = posts.Select(p => p.Id).ToList();
        var userIds  = posts.Select(p => p.UserId).Distinct().ToList();
        var placeIds = posts.Select(p => p.PlaceId).Distinct().ToList();

        // ── STEP 3: Bulk loads — 4 queries, zero N+1 ─────────────────────────
        var mediaTask = _db.PostMedia
            .Where(m => postIds.Contains(m.PostId))
            .Select(m => new { m.PostId, m.Url })
            .ToListAsync(ct);

        var userTask = (
            from u in _db.Users
            where userIds.Contains(u.Id)
            join pr in _db.UserProfiles on u.Id equals pr.UserId into prg
            from pr in prg.DefaultIfEmpty()
            select new
            {
                u.Id, u.Username,
                DisplayName     = pr != null ? pr.DisplayName     : null,
                ProfileImageUrl = pr != null ? pr.ProfileImageUrl : null
            }
        ).ToListAsync(ct);

        var placeTask = _db.PlaceTranslations
            .Where(t => placeIds.Contains(t.PlaceId))
            .Select(t => new { t.PlaceId, t.LanguageId, t.Name })
            .ToListAsync(ct);

        var likedTask = _db.PostLikes
            .Where(l => l.UserId == request.UserId && postIds.Contains(l.PostId))
            .Select(l => l.PostId)
            .ToListAsync(ct);

        await Task.WhenAll(mediaTask, userTask, placeTask, likedTask);

        // ── STEP 4: In-memory projection ──────────────────────────────────────
        var mediaByPost = mediaTask.Result
            .GroupBy(m => m.PostId)
            .ToDictionary(g => g.Key,
                          g => (IReadOnlyList<string>)g.Select(m => m.Url).ToList());

        var userById = userTask.Result.ToDictionary(u => u.Id);

        var nameByPlace = placeTask.Result
            .GroupBy(t => t.PlaceId)
            .ToDictionary(
                g => g.Key,
                g => (g.FirstOrDefault(t => t.LanguageId == 1) ?? g.First()).Name);

        var likedSet = likedTask.Result.ToHashSet();

        var dtos = posts.Select(p =>
        {
            userById.TryGetValue(p.UserId, out var u);
            return new FeedPostDto(
                p.Id,
                new FeedUserDto(p.UserId,
                    u?.Username ?? string.Empty,
                    u?.DisplayName,
                    u?.ProfileImageUrl),
                new FeedPlaceDto(p.PlaceId,
                    nameByPlace.GetValueOrDefault(p.PlaceId, string.Empty)),
                p.Caption,
                mediaByPost.GetValueOrDefault(p.Id, []),
                p.LikeCount,
                p.CommentCount,
                p.CreatedAt,
                likedSet.Contains(p.Id));
        }).ToList();

        // ── STEP 5: Build next cursor from last item ───────────────────────────
        // Fallback responses don't support cursor pagination (they're first-page only).
        var last     = posts[^1];
        var cursor   = new FeedCursor(last.FeedScore, last.CreatedAt, last.Id);
        var hasMore  = !isFallback && posts.Count == pageSize;
        var response = new FeedResponse(dtos, hasMore ? cursor : null, hasMore);

        if (!hasCursor) _cache.Set(cacheKey, response, CacheTtl);

        sw.Stop();
        _logger.LogInformation(
            "GetFollowingFeed — {Count} posts, hasMore={HasMore}, fallback={Fallback} in {Ms}ms",
            dtos.Count, hasMore, isFallback, sw.ElapsedMilliseconds);

        return ApiResult<FeedResponse>.Ok(response);
    }
}
